# Data Processing and Cleaning

Data: https://www.kaggle.com/datasets/rmisra/news-headlines-dataset-for-sarcasm-detection/data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_json("../data/Sarcasm_Headlines_Dataset.json", lines=True)
df.head()

,article_link,headline,is_sarcastic
0,https://www.huffingtonpost.com/entry/versace-b...,former versace store clerk sues over secret 'b...,0
1,https://www.huffingtonpost.com/entry/roseanne-...,the 'roseanne' revival catches up to our thorn...,0
2,https://local.theonion.com/mom-starting-to-fea...,mom starting to fear son's web series closest ...,1
3,https://politics.theonion.com/boehner-just-wan...,"boehner just wants wife to listen, not come up...",1
4,https://www.huffingtonpost.com/entry/jk-rowlin...,j.k. rowling wishes snape happy birthday in th...,0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26709 entries, 0 to 26708
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   article_link  26709 non-null  str
 1   headline      26709 non-null  str
 2   is_sarcastic  26709 non-null  int64
dtypes: int64(1), str(2)
memory usage: 626.1 KB

In [3]:
df.describe()

       is_sarcastic
count  26709.000000
mean       0.438953
std        0.496269
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000

In [4]:
df.columns

Index(['article_link', 'headline', 'is_sarcastic'], dtype='str')

In [5]:
# Drop article link
df = df[['headline', 'is_sarcastic']]

In [6]:
df.to_csv("../data/sarcasm_cleaned.csv", index=False)

In [7]:
df_raw = pd.read_json("../data/Sarcasm_Headlines_Dataset.json", lines=True)

df_raw.to_csv("../data/sarcasm_raw.csv", index=False)

# Exploratory Data Analysis